[project]
name = "urth"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "bs4>=0.0.2",
    "ebooklib>=0.19",
    "inflect>=7.5.0",
    "pyglossary>=5.1.0",
    "typer>=0.17.3",
    "typing-extensions>=4.15.0",
]
